// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPr549k_jtXGB8w-34Xv7Qbh8DVDjPdkg',
    appId: '1:83563939649:web:316f609215b3fcc34d03c0',
    messagingSenderId: '83563939649',
    projectId: 'blooddonation-7f784',
    authDomain: 'blooddonation-7f784.firebaseapp.com',
    storageBucket: 'blooddonation-7f784.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS1-0Z5sDUJcMAgLnCrtIQCgMEaV25T-c',
    appId: '1:83563939649:android:fc81b2d9276f5c424d03c0',
    messagingSenderId: '83563939649',
    projectId: 'blooddonation-7f784',
    storageBucket: 'blooddonation-7f784.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASNWR8UVLwVJJIXQ9_KrkWP-pkrsecQjw',
    appId: '1:83563939649:ios:dae67422052e7fdd4d03c0',
    messagingSenderId: '83563939649',
    projectId: 'blooddonation-7f784',
    storageBucket: 'blooddonation-7f784.appspot.com',
    iosBundleId: 'com.example.blooddonation',
  );
}
